
FROM php:8.2.4-apache
RUN a2enmod rewrite
RUN apt-get update && apt-get install -y \
    git \
    zip \
    unzip \
    && docker-php-ext-install pdo_mysql
RUN docker-php-ext-install mysqli
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
RUN composer require laravel/socialite

COPY . /var/www/html/
WORKDIR /var/www/html 
